package com.wingmark.backend.exception;

/** Machine-readable error codes returned as {@code ErrorResponse.code}. Never rename or repurpose one. */
public enum ErrorCode {
    // 400
    VALIDATION_FAILED,
    AGE_NOT_CONFIRMED,
    MALFORMED_REQUEST,
    INVALID_PARAMETER,
    BAD_REQUEST,
    OBSERVED_AT_IN_FUTURE,
    SAME_PASSWORD,
    WEAK_PASSWORD,
    PASSWORD_BREACHED,
    INVALID_PROFILE_PICTURE,
    INVALID_BOUNDS,
    INVALID_OR_EXPIRED_CODE,
    INVALID_FILE,
    TERMS_NOT_ACCEPTED,
    PRIVACY_NOT_ACCEPTED,
    CONSENT_VERSION_MISMATCH,
    // 401
    UNAUTHENTICATED,
    INVALID_CREDENTIALS,
    INVALID_OR_EXPIRED_TOKEN,
    // 403
    FORBIDDEN,
    PHOTO_QUOTA_EXCEEDED,
    EMAIL_NOT_VERIFIED,
    WRONG_PASSWORD,
    CANNOT_MODIFY_SELF,
    // 404 / 405 / 406
    NOT_FOUND,
    METHOD_NOT_ALLOWED,
    NOT_ACCEPTABLE,
    // 409
    CONFLICT,
    EMAIL_TAKEN,
    USERNAME_TAKEN,
    LAST_ADMIN,
    // 413 / 415 / 422 / 429
    FILE_TOO_LARGE,
    REQUEST_TOO_LARGE,
    UNSUPPORTED_MEDIA_TYPE,
    INVALID_REFERENCE,
    RATE_LIMITED,
    // 5xx
    EXTERNAL_SERVICE_ERROR,
    INTERNAL_ERROR
}
